apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus 
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: monitoring-kube-prometheus-prometheus
  serviceMonitorSelector: {} # Seleciona todos os ServiceMonitors do cluster
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
